### ISSUE TITLE
failed at "packer build eximchain-node.json"

### ISSUE THREAD

**Issue by hitbear518** [Eximchain/terraform-aws-eximchain-node#8]
I setup up my aws access key, 
after "ssh-keygen -t rsa -f ~/.ssh/eximchain-node" and "ssh-add ~/.ssh/eximchain-node",
I stuck on "packer build eximchain-node.json"
with "Permission denied (publickey)"

![image](https://user-images.githubusercontent.com/5070531/49379978-80c80480-f74b-11e8-979d-6b249c4d3269.png)

**Comment by Lsquared13** [comment]
Hello and thank you for your interest in using this tool.

Turns out there was a line in there forcing all `git clone` operations to use SSH instead of HTTP, causing the commands to fail if you do not have an SSH key in your agent which is uploaded to GitHub.

I will be pushing a fix shortly. Once this issue is closed, feel free to pull the latest version and give it another try.
